### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by captcookie** [Ellpeck/Slingshot#2]
while testing the ammo, i was wondering if there was a ammo bag that it could auto use from bc if i have enderpearls i dont want to use in my inventory, its possible they could be randomly used by the sling shot. sadface

or allow the player to right click the slingshot with stacks of item preference like a ammo slot kinda like with its on inventory slot. i dunno. I just want the mod to be more useful for my zelda mod pack use. gj either way :D

**Comment by Ellpeck** [comment]
The slingshot picks items in the offhand first, then in the hotbar, and then starting from the top left of the inventory. Just place your items in that order and the ender pearls won't be picked.

**Comment by captcookie** [comment]
works thanks!
